name: speak_sphere
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf
        - asset: assets/fonts/JosefinSans-Light.ttf
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
        - asset: assets/fonts/JosefinSans-Thin.ttf


